// HomeCareForm.js
import React, { useState, useRef, useEffect } from "react";
import HomeCareAddress from "./HomeCareAddress";
import HomeCareBasicInformation from "./HomeCareBasicInformation";
import HomeCareServiceDetails from "./HomeCareServiceDetails";
import HomeCareWorkerDetails from "./HomeCareWorkerDetails";
import HomeCarePaymentDetails from "./HomeCarePaymentDetails";
import firebaseDB from "../../firebase";
import { useAuth } from "../../context/AuthContext";

// Helper: compute next HM id from an array of ids
function computeNextHMIdFromList(ids = [], defaultPrefix = "HM-", padLength = 2) {
  let maxNum = 0;
  ids.forEach((s) => {
    if (!s) return;
    const m = String(s).trim().match(/^HM-(\d+)$/);
    if (!m) return;
    const num = parseInt(m[1], 10) || 0;
    if (num > maxNum) maxNum = num;
  });
  const next = maxNum + 1;
  const padded = String(next).padStart(padLength, "0");
  return `${defaultPrefix}${padded}`;
}

// Scan HomeCare/ClientData to find all id candidates and compute next id
async function fetchLastHomeCareClientId(firebaseDBRef) {
  try {
    const ids = [];

    // Read HomeCare/ClientData
    try {
      const snap = await firebaseDBRef.child("HomeCare/ClientData").once("value");
      if (snap.exists()) {
        snap.forEach((child) => {
          const v = child.val() || {};
          if (v.idNo) ids.push(String(v.idNo));
          else if (v.clientId) ids.push(String(v.clientId));
        });
      }
    } catch (e) {
      console.warn("fetch HomeCare/ClientData failed", e);
    }

    if (ids.length === 0) return "HM-01";

    let padLen = 2;
    ids.forEach((s) => {
      const m = String(s).trim().match(/^HM-(\d+)$/);
      if (m) {
        const digitsLen = m[1].length;
        if (digitsLen > padLen) padLen = digitsLen;
      }
    });

    return computeNextHMIdFromList(ids, "HM-", padLen);
  } catch (err) {
    console.warn("fetchLastHomeCareClientId error", err);
    return "HM-01";
  }
}

const formatDateForInput = (v) => {
  if (!v && v !== 0) return "";
  const d = new Date(v);
  if (isNaN(d)) return "";
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
};

const parseDateSafe = (v) => {
  if (!v && v !== 0) return null;
  if (v instanceof Date && !isNaN(v)) return v;
  const d = new Date(v);
  if (!isNaN(d)) return d;
  const s = String(v);
  const m = s.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);
  if (m) return new Date(Number(m[3]), Number(m[2]) - 1, Number(m[1]));
  return null;
};

const addDaysToDate = (d, days) => {
  const copy = new Date(d);
  copy.setDate(copy.getDate() + Number(days || 0));
  return copy;
};

function emptyPayment() {
  return {
    id: Date.now(),
    paymentMethod: "cash",
    paidAmount: "",
    balance: "",
    receiptNo: "",
    bookNo: "",
    reminderDays: "",
    reminderDate: "",
    date: "",
    remarks: "",
    addedById: null,
    addedByName: "",
    addedAt: "",
  };
}

function emptyWorker() {
  return {
    id: Date.now(),
    workerIdNo: "",
    name: "",
    startingDate: "",
    endingDate: "",
    mobile1: "",
    mobile2: "",
    basic: "",
    remarks: "",
  };
}

const getInitialFormData = () => ({
  // Basic Details
  idNo: "",
  clientName: "",
  gender: "",
  careOf: "",
  location: "",
  km: "",
  mobileNo1: "",
  mobileNo2: "",
  googleLocation: "",
  
  // Address
  doorNo: "",
  landmark: "",
  street: "",
  villageTown: "",
  mandal: "",
  district: "",
  state: "",
  pincode: "",
  
  // Service Details
  typeOfService: "",
  servicePeriod: "",
  timeSlot: "",
  serviceCharges: "",
  startingDate: "",
  pageNo: "",
  aboutClientRecipients: "",
  aboutWork: "",
  
  // Creation stamps
  createdById: null,
  createdByName: "",
  createdAt: "",
  
  workers: [emptyWorker()],
  payments: [emptyPayment()],
});

export default function HomeCareClientForm({ isOpen, onClose }) {
  const [step, setStep] = useState(1);
  const totalSteps = 5;
  const [formData, setFormData] = useState(getInitialFormData());
  const [errors, setErrors] = useState({ workers: [{}], payments: [{}] });
  const [idAutoGenerated, setIdAutoGenerated] = useState(false);
  const [showModal, setShowModal] = useState(false);
  const [submittedClientData, setSubmittedClientData] = useState(null);
  const [dupModal, setDupModal] = useState({ show: false, idNo: "", name: "" });

  const stepTitles = [
    "",
    "Basic Details",
    "Address",
    "Service Details",
    "Worker Details",
    "Payment Details",
  ];

  const lastClickedButtonRef = useRef(null);
  const { user: authUser } = useAuth() || { user: null };

  // Auto-generate ID when modal opens
  useEffect(() => {
    if (!isOpen) return;
    let mounted = true;

    (async () => {
      try {
        if (!formData.idNo || String(formData.idNo).trim() === "") {
          const nextId = await fetchLastHomeCareClientId(firebaseDB);
          if (mounted && nextId) {
            setFormData((prev) => ({ ...prev, idNo: nextId }));
            setIdAutoGenerated(true);
          }
        }
      } catch (err) {
        console.warn("Auto-generate home care client id failed", err);
      }
    })();

    return () => {
      mounted = false;
    };
  }, [isOpen]);

  const getEffectiveUserId = () => {
    const u = authUser || {};
    return (
      u.uid ||
      u.id ||
      u.dbId ||
      u.key ||
      u.dbUsername ||
      u.username ||
      u.email ||
      null
    );
  };

  const getEffectiveUserName = () => {
    const u = authUser || {};
    const raw =
      u.name ||
      u.displayName ||
      u.dbName ||
      u.username ||
      u.dbUsername ||
      u.email ||
      "";
    return String(raw).replace(/@.*/, "").trim() || "System";
  };

  const handleChange = (e, section, index = null) => {
    const { name, value } = e.target;

    if (name === "idNo" && idAutoGenerated) {
      setIdAutoGenerated(false);
    }

    if (index !== null && section) {
      const updatedArray = Array.isArray(formData[section]) ? [...formData[section]] : [];
      const row = { ...(updatedArray[index] || {}) };
      row[name] = value;

      if (section === "payments") {
        if (name === "reminderDays") {
          const days = Number(value) || 0;
          const base = parseDateSafe(row.date) || new Date();
          const adjusted = days - 1;
          if (adjusted >= 0) row.reminderDate = formatDateForInput(addDaysToDate(base, adjusted));
          else row.reminderDate = "";
        }
        if (name === "date" && row.reminderDays) {
          const days = Number(row.reminderDays) || 0;
          const base = parseDateSafe(value) || new Date();
          const adjusted = days - 1;
          if (adjusted >= 0) row.reminderDate = formatDateForInput(addDaysToDate(base, adjusted));
          else row.reminderDate = "";
        }
      }

      updatedArray[index] = row;
      setFormData((prev) => ({ ...prev, [section]: updatedArray }));

      if (section === "workers" || section === "payments") {
        const arrErrs = (errors[section] || []).map((obj, i) => (i === index ? { ...(obj || {}), [name]: "" } : obj));
        setErrors((prev) => ({ ...prev, [section]: arrErrs }));
      } else {
        setErrors((prev) => ({ ...prev, [name]: "" }));
      }
    } else {
      setFormData((prev) => ({ ...prev, [name]: value }));
      setErrors((prev) => ({ ...prev, [name]: "" }));
    }
  };

  const addWorker = () => {
    setFormData((prev) => ({ ...prev, workers: [...(prev.workers || []), emptyWorker()] }));
    setErrors((prev) => ({ ...prev, workers: [...(prev.workers || []), {}] }));
  };

  const removeWorker = (index) => {
    setFormData((prev) => ({ ...prev, workers: (prev.workers || []).filter((_, i) => i !== index) }));
    setErrors((prev) => ({ ...prev, workers: (prev.workers || []).filter((_, i) => i !== index) }));
  };

  const addPayment = () => {
    setFormData((prev) => ({ ...prev, payments: [...(prev.payments || []), emptyPayment()] }));
    setErrors((prev) => ({ ...prev, payments: [...(prev.payments || []), {}] }));
  };

  const removePayment = (index) => {
    setFormData((prev) => ({ ...prev, payments: (prev.payments || []).filter((_, i) => i !== index) }));
    setErrors((prev) => ({ ...prev, payments: (prev.payments || []).filter((_, i) => i !== index) }));
  };

  const validateStep = (currentStep) => {
    let newErrors = { ...errors };
    let isValid = true;

    if (currentStep === 1) {
      if (!formData.idNo || !formData.idNo.trim()) {
        newErrors.idNo = "ID No is required";
        isValid = false;
      } else if (!/^HM-\d{2,}$/.test(formData.idNo)) {
        newErrors.idNo = "ID No must be (e.g., HM-01)";
        isValid = false;
      }
      if (!formData.clientName || !formData.clientName.trim()) {
        newErrors.clientName = "Client Name is required";
        isValid = false;
      }
      if (!formData.gender) {
        newErrors.gender = "Gender is required";
        isValid = false;
      }
      if (!formData.location || !formData.location.trim()) {
        newErrors.location = "Location is required";
        isValid = false;
      }
      if (!formData.mobileNo1) {
        newErrors.mobileNo1 = "Mobile No 1 is required";
        isValid = false;
      } else if (!/^\d{10}$/.test(formData.mobileNo1)) {
        newErrors.mobileNo1 = "Mobile No 1 must be exactly 10 digits";
        isValid = false;
      }
      if (formData.mobileNo2 && !/^\d{10}$/.test(formData.mobileNo2)) {
        newErrors.mobileNo2 = "Mobile No 2 must be exactly 10 digits";
        isValid = false;
      }
    }

    if (currentStep === 2) {
      if (!formData.doorNo || !formData.doorNo.trim()) {
        newErrors.doorNo = "Door No is required";
        isValid = false;
      }
      if (!formData.villageTown || !formData.villageTown.trim()) {
        newErrors.villageTown = "Village/Town is required";
        isValid = false;
      }
      if (!formData.mandal || !formData.mandal.trim()) {
        newErrors.mandal = "Mandal is required";
        isValid = false;
      }
      if (!formData.district || !formData.district.trim()) {
        newErrors.district = "District is required";
        isValid = false;
      }
      if (!formData.state || !formData.state.trim()) {
        newErrors.state = "State is required";
        isValid = false;
      }
      if (!formData.pincode) {
        newErrors.pincode = "Pincode is required";
        isValid = false;
      } else if (!/^\d{5}$/.test(formData.pincode)) {
        newErrors.pincode = "Pincode must be 5 digits";
        isValid = false;
      }
    }

    if (currentStep === 3) {
      if (!formData.typeOfService) {
        newErrors.typeOfService = "Type of Service is required";
        isValid = false;
      }
      if (!formData.servicePeriod || !formData.servicePeriod.trim()) {
        newErrors.servicePeriod = "Service Period is required";
        isValid = false;
      }
      if (!formData.timeSlot) {
        newErrors.timeSlot = "Time Slot is required";
        isValid = false;
      }
      if (!formData.serviceCharges) {
        newErrors.serviceCharges = "Service Charges is required";
        isValid = false;
      } else if (isNaN(Number(formData.serviceCharges)) || Number(formData.serviceCharges) <= 0) {
        newErrors.serviceCharges = "Service Charges must be a positive number";
        isValid = false;
      }
      if (!formData.startingDate) {
        newErrors.startingDate = "Starting Date is required";
        isValid = false;
      }
      if (!formData.aboutClientRecipients || !formData.aboutClientRecipients.trim()) {
        newErrors.aboutClientRecipients = "About Client Recipients is required";
        isValid = false;
      }
      if (!formData.aboutWork || !formData.aboutWork.trim()) {
        newErrors.aboutWork = "About Work is required";
        isValid = false;
      }
    }

    if (currentStep === 4) {
      const workersErrors = (formData.workers || []).map((w) => {
        const e = {};
        if (!w.workerIdNo || !w.workerIdNo.trim()) {
          e.workerIdNo = "Worker ID is required";
          isValid = false;
        }
        if (!w.name || !w.name.trim()) {
          e.name = "Worker Name is required";
          isValid = false;
        }
        if (!w.startingDate) {
          e.startingDate = "Starting Date is required";
          isValid = false;
        }
        if (!w.mobile1) {
          e.mobile1 = "Mobile 1 is required";
          isValid = false;
        } else if (!/^\d{10}$/.test(w.mobile1)) {
          e.mobile1 = "Mobile 1 must be exactly 10 digits";
          isValid = false;
        }
        if (w.mobile2 && !/^\d{10}$/.test(w.mobile2)) {
          e.mobile2 = "Mobile 2 must be exactly 10 digits";
          isValid = false;
        }
        return e;
      });
      newErrors.workers = workersErrors;
    }

    if (currentStep === 5) {
      const payments = Array.isArray(formData.payments) ? formData.payments : [];
      let atLeastOneValid = false;

      const paymentsErrors = payments.map((p) => {
        const e = {};

        const hasValue =
          (p.paidAmount && String(p.paidAmount).trim() !== "") ||
          (p.receiptNo && String(p.receiptNo).trim() !== "") ||
          (p.date && String(p.date).trim() !== "") ||
          (p.paymentMethod && String(p.paymentMethod).trim() !== "");

        if (!hasValue) {
          return e;
        }

        if (!p.paymentMethod) {
          e.paymentMethod = "Payment method is required";
          isValid = false;
        }
        if (p.paidAmount === "" || p.paidAmount === null || typeof p.paidAmount === "undefined") {
          e.paidAmount = "Paid Amount is required";
          isValid = false;
        } else if (isNaN(Number(p.paidAmount)) || Number(p.paidAmount) <= 0) {
          e.paidAmount = "Paid Amount must be a positive number";
          isValid = false;
        }

        if (!p.receiptNo || !String(p.receiptNo).trim()) {
          e.receiptNo = "Receipt No is required";
          isValid = false;
        }

        if (!p.date || !String(p.date).trim()) {
          e.date = "Payment Date is required";
          isValid = false;
        }

        if (Object.keys(e).length === 0) {
          atLeastOneValid = true;
        }

        return e;
      });

      if (!atLeastOneValid) {
        isValid = false;
        if (paymentsErrors.length > 0) {
          const first = paymentsErrors[0] || {};
          paymentsErrors[0] = {
            ...first,
            paidAmount: first.paidAmount || "Enter a valid payment",
            paymentMethod: first.paymentMethod || "Payment method is required",
            receiptNo: first.receiptNo || "Receipt No is required",
            date: first.date || "Payment Date is required",
          };
        }
      }

      newErrors.payments = paymentsErrors;
    }

    setErrors((prev) => ({ ...prev, ...newErrors }));
    return isValid;
  };

  const nextStep = async () => {
    if (!validateStep(step)) return;

    if (step === 1) {
      try {
        const idToCheck = (formData.idNo || "").trim();
        const queryRef = firebaseDB.child("HomeCare/ClientData").orderByChild("idNo").equalTo(idToCheck);
        const snap = await queryRef.once("value");
        if (snap.exists()) {
          let foundName = "";
          const val = snap.val();
          if (val && typeof val === "object") {
            const firstKey = Object.keys(val)[0];
            if (firstKey) foundName = val[firstKey]?.clientName || "";
          }
          setDupModal({ show: true, idNo: idToCheck, name: foundName });
          return;
        }
      } catch (err) {
        console.error("Duplicate ID check failed:", err);
      }
    }

    const next = Math.min(totalSteps, step + 1);

    if (next === 5) {
      if (!Array.isArray(formData.payments) || formData.payments.length === 0) {
        setFormData((prev) => ({ ...prev, payments: [emptyPayment()] }));
      }
      setErrors((prev) => ({ ...prev, payments: (formData.payments || []).map(() => ({})) }));
    }

    setStep(next);
  };

  const prevStep = () => setStep((s) => Math.max(1, s - 1));

  const handleSubmit = async (e) => {
    e.preventDefault();
    const submitter = (e && e.nativeEvent && e.nativeEvent.submitter) || null;
    const lastClicked = lastClickedButtonRef.current || null;
    const active = (typeof document !== "undefined" && document.activeElement) ? document.activeElement : null;
    const finalSubmitId = "homecare-client-submit-button";
    const triggeredByFinalButton = (
      (submitter && submitter.id === finalSubmitId) ||
      (lastClicked && lastClicked.id === finalSubmitId) ||
      (active && active.id === finalSubmitId)
    );

    if (!triggeredByFinalButton && step < totalSteps) {
      if (!validateStep(step)) return;
      const next = Math.min(totalSteps, step + 1);
      if (next === 5) {
        if (!Array.isArray(formData.payments) || formData.payments.length === 0) {
          setFormData((prev) => ({ ...prev, payments: [emptyPayment()] }));
        }
        setErrors((prev) => ({ ...prev, payments: (formData.payments || []).map(() => ({})) }));
      }
      setStep(next);
      return;
    }

    if (!triggeredByFinalButton) {
      return;
    }

    if (step < totalSteps) {
      return;
    }

    if (!validateStep(step)) return;

    const nowIso = new Date().toISOString();
    const effId = getEffectiveUserId();
    const effName = getEffectiveUserName();

    const normalizedPayments = Array.isArray(formData.payments)
      ? formData.payments.map((p) => ({
        ...p,
        addedById: p.addedById || effId,
        addedByName: (p.addedByName || effName).toString().replace(/@.*/, ""),
        addedAt: p.addedAt || p.timestamp || p.date || nowIso,
      }))
      : [];

    const dataToSave = {
      // Basic Details
      idNo: formData.idNo || "",
      clientName: formData.clientName || "",
      gender: formData.gender || "",
      careOf: formData.careOf || "",
      location: formData.location || "",
      km: formData.km || "",
      mobileNo1: formData.mobileNo1 || "",
      mobileNo2: formData.mobileNo2 || "",
      googleLocation: formData.googleLocation || "",
      
      // Address
      doorNo: formData.doorNo || "",
      landmark: formData.landmark || "",
      street: formData.street || "",
      villageTown: formData.villageTown || "",
      mandal: formData.mandal || "",
      district: formData.district || "",
      state: formData.state || "",
      pincode: formData.pincode || "",
      
      // Service Details
      typeOfService: formData.typeOfService || "",
      servicePeriod: formData.servicePeriod || "",
      timeSlot: formData.timeSlot || "",
      serviceCharges: formData.serviceCharges || "",
      startingDate: formData.startingDate || "",
      pageNo: formData.pageNo || "",
      aboutClientRecipients: formData.aboutClientRecipients || "",
      aboutWork: formData.aboutWork || "",
      
      workers: Array.isArray(formData.workers) ? formData.workers.map(({ id, ...w }) => w) : [],
      
      // Creation stamps
      createdById: effId,
      createdByName: effName,
      createdAt: nowIso,
      
      payments: normalizedPayments,
    };

    try {
      const newRef = await firebaseDB.child("HomeCare/ClientData").push(dataToSave);
      if (newRef && newRef.key) {
        setSubmittedClientData({ idNo: formData.idNo, clientName: formData.clientName });
        setShowModal(true);
        setFormData(getInitialFormData());
        setErrors({ workers: [{}], payments: [{}] });
        setStep(1);
        setIdAutoGenerated(false);
      }
    } catch (err) {
      console.error("Error saving to Firebase:", err);
      alert("Error saving to Firebase: " + (err.message || err));
    }
  };

  const renderStep = () => {
    switch (step) {
      case 1:
        return <HomeCareBasicInformation formData={formData} handleChange={handleChange} errors={errors} isViewMode={false} idDisabled={idAutoGenerated} />;
      case 2:
        return <HomeCareAddress formData={formData} handleChange={handleChange} errors={errors} isViewMode={false} />;
      case 3:
        return <HomeCareServiceDetails formData={formData} handleChange={handleChange} errors={errors} setErrors={setErrors} isViewMode={false} />;
      case 4:
        return <HomeCareWorkerDetails formData={formData} handleChange={handleChange} addWorker={addWorker} removeWorker={removeWorker} errors={errors} setErrors={setErrors} isViewMode={false} />;
      case 5:
        return <HomeCarePaymentDetails formData={formData} handleChange={handleChange} addPayment={addPayment} removePayment={removePayment} errors={errors} isViewMode={false} />;
      default:
        return null;
    }
  };

  if (!isOpen) return null;

  return (
    <div className="modal fade show" style={{ display: "block", backgroundColor: "rgba(3,3,3,0.9)" }}>
      <div className="modal-dialog modal-xl modal-dialog-centered client-form">
        <div className="modal-content">
          <div className="modal-header">
            <h5 className="modal-title">Home Care Client Information Form</h5>
            <button type="button" className="btn-close btn-close-white" onClick={onClose}></button>
          </div>

          <div className="modal-body">
            <div className="px-4 pt-3">
              <p className="text-center steps">Step {step} of {totalSteps}</p>
              <div className="progress mb-3">
                <div className="progress-bar bg-primary" role="progressbar" style={{ width: `${(step / totalSteps) * 100}%` }} />
              </div>
              <h4 className="text-center mb-3 form-steps">{stepTitles[step]}</h4>
            </div>

            <form
              onSubmit={handleSubmit}
              onClickCapture={(e) => {
                try {
                  const btn = e.target.closest && e.target.closest("button");
                  if (btn) lastClickedButtonRef.current = btn;
                } catch (err) {
                  // ignore
                }
              }}
              onKeyDown={(e) => {
                if (e.key === "Enter" && step < totalSteps) {
                  const tag = (e.target && e.target.tagName) ? e.target.tagName.toLowerCase() : "";
                  if (tag !== "textarea") {
                    e.preventDefault();
                  }
                }
              }}
            >
              <div className="card-body">{renderStep()}</div>

              <div className="card-footer d-flex justify-content-end w-100">
                {step > 1 && (
                  <button
                    type="button"
                    className="btn btn-secondary me-2"
                    onMouseDown={(e) => e.preventDefault()}
                    onClick={(e) => {
                      e.preventDefault();
                      prevStep();
                    }}
                  >
                    Previous
                  </button>
                )}

                {step < totalSteps ? (
                  <button
                    type="button"
                    className="btn btn-primary"
                    onMouseDown={(e) => e.preventDefault()}
                    onClick={(e) => {
                      e.preventDefault();
                      nextStep();
                    }}
                  >
                    Next
                  </button>
                ) : (
                  <button id="homecare-client-submit-button" type="submit" className="btn btn-success">Submit</button>
                )}
              </div>
            </form>
          </div>
        </div>
      </div>

      {showModal && (
        <div className="modal fade show" style={{ display: "block", background: "rgba(0,0,0,0.9)" }}>
          <div className="modal-dialog modal-dialog-centered">
            <div className="modal-content">
              <div className="modal-header bg-success">
                <h5 className="modal-title text-center text-white">Thank you!</h5>
                <button type="button" className="btn-close btn-white" onClick={() => { setShowModal(false); onClose(); }} />
              </div>
              <div className="modal-body">
                <p>Home Care Client form has been submitted successfully.</p>
                {submittedClientData && (
                  <div className="alert mt-3">
                    <strong>Client Details:</strong>
                    <div className="mt-2"><strong>ID:</strong> {submittedClientData.idNo}</div>
                    <div><strong>Client Name:</strong> {submittedClientData.clientName}</div>
                  </div>
                )}
              </div>
              <div className="modal-footer">
                <button type="button" className="btn btn-success" onClick={() => { setShowModal(false); onClose(); }}>OK</button>
              </div>
            </div>
          </div>
        </div>
      )}

      {dupModal.show && (
        <div className="modal fade show" style={{ display: "block", background: "rgba(0,0,0,0.9)" }}>
          <div className="modal-dialog modal-dialog-centered">
            <div className="modal-content">
              <div className="modal-header bg-danger">
                <h5 className="modal-title text-white">Duplicate Client ID</h5>
                <button type="button" className="btn-close btn-white" onClick={() => setDupModal({ show: false, idNo: "", name: "" })} />
              </div>
              <div className="modal-body">
                <p className="mb-0">Client ID <strong>{dupModal.idNo}</strong> already exists {dupModal.name ? <>with the name: <strong>{dupModal.name}</strong></> : ""}.</p>
                <p className="mt-2 mb-0">Please enter a new Client ID to continue.</p>
              </div>
              <div className="modal-footer">
                <button type="button" className="btn btn-secondary" onClick={() => setDupModal({ show: false, idNo: "", name: "" })}>OK</button>
                <button type="button" className="btn btn-outline-danger" onClick={() => { setFormData((prev) => ({ ...prev, idNo: "" })); setDupModal({ show: false, idNo: "", name: "" }); setIdAutoGenerated(false); }}>Clear ID</button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}